aspDotNet Calculator
romadanskiy/dr pull request #6
Opened 2020-10-12 11:03 UTC by romadanskiy

AspDotNet Calculator

2020-10-12 14:47 UTC, DimaCheg requested changes

2020-10-12 14:47 UTC, DimaCheg commented on Dr1/WebCalculator/CalculatorMiddleware.cs
> +        }
Либо валидация expression неправильная, либо я что-то делаю не так.
https://localhost:5001/?expression=1+1
>> Expression 1 1 is invalid
https://localhost:5001/?expression=1 - 1
>> Expression 1 - 1 is invalid

2020-10-12 15:02 UTC, romadanskiy commented on Dr1/WebCalculator/CalculatorMiddleware.cs
> +        }
@DimaCheg http запрос не распознает знак +, вместо него надо писать %2b :
https://localhost:5001/?expression=1%2b1

Писать нужно без пробела:
https://localhost:5001/?expression=1%2b1
https://localhost:5001/?expression=1-1
https://localhost:5001/?expression=1*1
https://localhost:5001/?expression=1/1

2020-11-09 15:55 UTC, DimaCheg approved these changes

2020-11-09 15:56 UTC, merged